const $ = (id) => document.getElementById(id);
const SAVE_KEY = 'sea-resort-fishing-v1';
const rarities = [
  {name:'Обычная', color:'#b9d5d7', value:35}, {name:'Редкая', color:'#55aaff', value:110},
  {name:'Эпическая', color:'#bf79ff', value:380}, {name:'Мифическая', color:'#ff9271', value:1250}, {name:'Легендарная', color:'#ffe06a', value:4200}
];
const locations = {
  pier:{name:'Лесное озеро', sub:'тихая бухта', desc:'Стартовая бухта с доступной пресноводной рыбой и лёгкой рябью.', fish:['Окунь речной','Плотва обыкновенная','Карась серебряный','Лещ обыкновенный','Карп обыкновенный']},
  ocean:{name:'Горное озеро', sub:'холодная вода', desc:'Глубокая чистая вода, быстрые волны и редкие холодноводные виды.', fish:['Форель ручьевая','Хариус европейский','Сиг европейский','Голец арктический','Форель радужная']},
  swamp:{name:'Туманные плавни', sub:'камышовые протоки', desc:'Тёмная вода, камыши и осторожные болотные хищники.', fish:['Щука обыкновенная','Линь обыкновенный','Сом европейский','Вьюн обыкновенный','Краснопёрка обыкновенная']}
};
const gear = {
  rods:[['Бамбуковая поплавочная удочка',0],['Ультралайтовый спиннинг',120],['Тяжёлый фидер',390],['Длинное карповое удилище',1200],['Троллинговый спиннинг',3800],['Карбоновое матчевое удилище',9000],['Дальнобойный фидер',22000],['Турнирное карповое удилище',52000]],
  knives:[['Рыбацкий нож',0],['Перламутровый нож',140],['Приливный клинок',450],['Нож бездны',1400],['Солнечный тесак',4400],['Клинок шкипера',10500],['Титановый филейник',25000],['Мастерский нож',60000]],
  hooks:[['Медный крючок',0],['Лунный крючок',110],['Звёздная связка',350],['Туманная сеть',1100],['Галактическая стая',3600],['Серебряный тройник',8600],['Штормовая оснастка',20500],['Коллекционерский набор',49000]],
  floats:[['Красно-белый поплавок',0],['Речной поплавок',90],['Дальний поплавок',280],['Ночной поплавок',850],['Турнирный поплавок',2600],['Штормовой поплавок',6500],['Светящийся поплавок',15500],['Мастерский поплавок',37000]],
  baits:[['Хлебный шарик',0],['Червь',80],['Опарыш',240],['Креветка',720],['Арома-микс',2200],['Раковая наживка',5400],['Трофейный бойл',13000],['Легендарный микс',31000]]
};
const pets = [{name:'Выдра Искра',icon:'🦦',bonus:'+20% к продаже',price:1000000,type:'money'}, {name:'Чайка Ветра',icon:'🕊️',bonus:'быстрее поклёвка',price:1250000,type:'speed'}, {name:'Морской лис',icon:'🦊',bonus:'+10% к редкой рыбе',price:1500000,type:'luck'}];
const rodImages=['assets/rods/rod-01.png','assets/rods/rod-02.png','assets/rods/rod-03.png','assets/rods/rod-04.png','assets/rods/rod-05.png','assets/rods/rod-06.png','assets/rods/rod-07.png','assets/rods/rod-08.png'];
const fishImages={'Окунь речной':'assets/fish/fish-01-perch.png','Плотва обыкновенная':'assets/fish/fish-02-roach.png','Карась серебряный':'assets/fish/fish-03-prussian-carp.png','Лещ обыкновенный':'assets/fish/fish-04-bream.png','Карп обыкновенный':'assets/fish/fish-05-common-carp.png','Форель ручьевая':'assets/fish/fish-06-brown-trout.png','Хариус европейский':'assets/fish/fish-07-grayling.png','Сиг европейский':'assets/fish/fish-08-whitefish.png','Голец арктический':'assets/fish/fish-09-arctic-char.png','Форель радужная':'assets/fish/fish-10-rainbow-trout.png','Щука обыкновенная':'assets/fish/fish-11-northern-pike.png','Линь обыкновенный':'assets/fish/fish-12-tench.png','Сом европейский':'assets/fish/fish-13-wels-catfish.png','Вьюн обыкновенный':'assets/fish/fish-14-weather-loach.png','Краснопёрка обыкновенная':'assets/fish/fish-15-rudd.png'};
const initial = {coins:30, rods:1, knives:1, hooks:1, floats:1, baits:1, location:'pier', inventory:[], discovered:[], journal:['Вы прибыли на Лесное озеро.'], pets:[], total:30, best:'—', xp:0, auctions:[], auctionLog:[], contract:{target:8,progress:0,reward:300}};
let state; try { state={...initial,...JSON.parse(localStorage.getItem(SAVE_KEY))}; } catch { state={...initial}; }
let charge=0, charging=false, castTimer, casting=false, pulling=false, pullTimer, reel=0, session=0, shop='rods';
const save=()=>localStorage.setItem(SAVE_KEY,JSON.stringify(state));
const roman=(n)=>['I','II','III','IV','V','VI','VII','VIII'][n-1];
const petBonus=(type)=>state.pets.some(p=>p.type===type);
const playerLevel=()=>Math.min(12,1+Math.floor(Math.sqrt(state.xp/120)));
const levelProgress=()=>{const level=playerLevel(),start=120*(level-1)**2,end=120*level**2;return level===12?100:Math.round((state.xp-start)/(end-start)*100)};
const locationLevels={pier:1,ocean:3,swamp:5};
const tierName=(level)=>rarities[Math.min(4,Math.ceil(level*5/8)-1)].name.toLowerCase();
console.assert(playerLevel()>=1&&playerLevel()<=12,'Некорректный уровень игрока');
function render(){
  settleAuctions();
  $('coins').textContent=state.coins.toLocaleString('ru-RU'); $('fishCount').textContent=state.inventory.length;
  $('rodLevel').textContent=roman(state.rods); $('knifeLevel').textContent=roman(state.knives); $('hookLevel').textContent=roman(state.hooks);
  $('hookName').textContent=gear.hooks[state.hooks-1][0]; $('locationLabel').textContent=`${locations[state.location].name} · ${locations[state.location].sub}`;
  $('bestCatch').textContent=state.best; $('game').className=`game location-${state.location}`;
  $('equippedRodImage').src=rodImages[state.rods-1]; $('equippedRodImage').alt=gear.rods[state.rods-1][0];
  $('playerLevel').textContent=playerLevel(); $('xpBar').style.width=levelProgress()+'%'; $('contractLabel').textContent=`Контракт: ${state.contract.progress}/${state.contract.target} · ${state.contract.reward} ◉`;
  renderKeepnet(); renderMap(); renderBag(); renderProfile(); renderJournal(); renderIndex(); renderShop(); renderPets(); renderAuctions(); save();
}
function openModal(id){ $(id).classList.add('open'); render(); }
function closeAll(){document.querySelectorAll('.modal').forEach(x=>x.classList.remove('open'))}
function note(text){$('castMessage').textContent=text}
function time(){session++; $('sessionTime').textContent=`${String(Math.floor(session/60)).padStart(2,'0')}:${String(session%60).padStart(2,'0')}`}
setInterval(time,1000);
class ProceduralScene {
  constructor(canvas){this.c=canvas;this.x=50;this.y=61;this.cast=0;this.reel=0;this.biting=false;this.pulling=false;this.fish=null;this.t0=performance.now();this.resize();addEventListener('resize',()=>this.resize());requestAnimationFrame(t=>this.frame(t))}
  resize(){const d=Math.min(devicePixelRatio||1,2),r=this.c.getBoundingClientRect();this.w=Math.max(1,r.width);this.h=Math.max(1,r.height);this.c.width=this.w*d;this.c.height=this.h*d;this.g=this.c.getContext('2d');this.g.setTransform(d,0,0,d,0,0)}
  startCast(power){this.cast=power;this.reel=0;this.x=31+power*.55;this.y=57+power*.075;this.biting=false;this.fish=null}
  clear(){this.cast=0;this.reel=0;this.biting=false;this.pulling=false;this.fish=null}
  floatPoint(w,h){const p=this.pulling?this.reel/100:0;return{x:w*(this.x+(56-this.x)*p)/100,y:h*(this.y+(84-this.y)*p)/100}}
  frame(now){const t=(now-this.t0)/1000,g=this.g,w=this.w,h=this.h;g.clearRect(0,0,w,h);this.ripples(g,w,h,t);this.line(g,w,h,t);if(this.cast)this.bobber(g,w,h,t);requestAnimationFrame(n=>this.frame(n))}
  ripples(g,w,h,t){if(!this.cast)return;const p=this.floatPoint(w,h);for(let i=0;i<3;i++){const r=(t*30+i*19)%70;g.strokeStyle=`rgba(225,255,255,${.46-r/170})`;g.lineWidth=1.2;g.beginPath();g.ellipse(p.x,p.y,r,r*.3,0,0,Math.PI*2);g.stroke()}}
  line(g,w,h,t){if(!this.cast)return;const p=this.floatPoint(w,h);g.save();g.strokeStyle='#e5fbffba';g.lineWidth=1;g.beginPath();g.moveTo(w*.86,h*.06);g.quadraticCurveTo(w*.75,h*.28+Math.sin(t*2)*5,p.x,p.y);g.stroke();g.restore()}
  sky(g,w,h,t,loc){const sets={pier:['#103c71','#ef9274','#ffd68a'],ocean:['#06345f','#6e9fc0','#d5dbca'],swamp:['#1a302a','#63765c','#b0a77c']}[loc];const sky=g.createLinearGradient(0,0,0,h*.58);sky.addColorStop(0,sets[0]);sky.addColorStop(.72,sets[1]);sky.addColorStop(1,sets[2]);g.fillStyle=sky;g.fillRect(0,0,w,h*.6);const sx=w*.77,sy=h*.22;const sun=g.createRadialGradient(sx,sy,2,sx,sy,h*.11);sun.addColorStop(0,'#fff9cf');sun.addColorStop(.35,'#ffe8a4');sun.addColorStop(1,'#ffcf8400');g.fillStyle=sun;g.fillRect(0,0,w,h*.6);g.fillStyle='rgba(255,246,232,.35)';for(let i=0;i<5;i++){let x=((i*263+t*9)% (w+220))-110,y=h*(.12+i*.055);g.beginPath();g.ellipse(x,y,90,12,0,0,Math.PI*2);g.ellipse(x+45,y-10,38,20,0,0,Math.PI*2);g.fill()}g.fillStyle=loc==='swamp'?'#244437':'#1a5660';g.beginPath();g.moveTo(0,h*.51);for(let x=0;x<=w;x+=35){const y=h*(.43+((Math.sin(x*.027)+Math.sin(x*.071))*0.025));g.lineTo(x,y)}g.lineTo(w,h*.57);g.lineTo(0,h*.57);g.fill();if(loc!=='swamp'){g.fillStyle='#263f4b';g.beginPath();g.moveTo(w*.73,h*.47);g.lineTo(w*.76,h*.39);g.lineTo(w*.79,h*.47);g.fill();g.fillRect(w*.755,h*.445,w*.045,2)}}
  water(g,w,h,t,loc){const top=h*.51,sets={pier:['#1786a0','#043150'],ocean:['#087da6','#012642'],swamp:['#496f49','#102d2b']}[loc],grad=g.createLinearGradient(0,top,0,h);grad.addColorStop(0,sets[0]);grad.addColorStop(1,sets[1]);g.fillStyle=grad;g.fillRect(0,top,w,h-top);for(let row=0;row<18;row++){const y=top+row*18;g.strokeStyle=`rgba(210,255,255,${.11-row*.004})`;g.lineWidth=1;g.beginPath();for(let x=0;x<=w;x+=8){const wave=Math.sin(x*.025+t*(1.5+(loc==='ocean'?1:0))+row*.8)*((row+2)/10)+Math.sin(x*.07-t*1.7)*1.5; x?g.lineTo(x,y+wave):g.moveTo(x,y+wave)}g.stroke()}const rx=w*.77;for(let i=0;i<18;i++){const yy=top+18+i*i*1.5;const ww=Math.max(3,5+i*5);g.fillStyle=`rgba(255,239,178,${.22-i*.01})`;g.fillRect(rx-ww/2+Math.sin(t*3+i)*5,yy,ww,1.5)}if(this.cast){const x=w*this.x/100,y=h*this.y/100;for(let i=0;i<3;i++){const r=((t*42+i*19)%72);g.strokeStyle=`rgba(220,255,255,${.5-r/145})`;g.beginPath();g.ellipse(x,y,r,r*.3,0,0,Math.PI*2);g.stroke()}}}
  pier(g,w,h){g.save();g.fillStyle='#51311f';g.beginPath();g.moveTo(0,h);g.lineTo(w,h);g.lineTo(w*.72,h*.78);g.lineTo(w*.28,h*.78);g.closePath();g.fill();g.strokeStyle='#9a6139';g.lineWidth=3;for(let i=0;i<9;i++){const x=w*.28+(w*.44/8)*i;g.beginPath();g.moveTo(x,h*.78);g.lineTo(x+(x-w*.5)*.7,h);g.stroke()}g.restore()}
  rod(g,w,h,t){const styles=[['#25130b','#c79655','#c98c64'],['#101419','#a8b7bd','#29323a'],['#302017','#d2a642','#c79749'],['#1a2545','#7cc9f0','#263d60'],['#36151b','#dc545d','#64212a'],['#0d1926','#78c7d9','#1d4052'],['#1d1d24','#ddeeff','#747786'],['#1a102d','#e9cf5b','#6d4b9f']][state.rods-1],baseX=w*.51,baseY=h*1.03,point=this.cast?this.floatPoint(w,h):{x:baseX+w*.13,y:baseY-h*.33},tipX=point.x,tipY=point.y,bend=this.biting?34:this.pulling?21:8;g.save();g.lineCap='round';g.strokeStyle=styles[0];g.lineWidth=13;g.beginPath();g.moveTo(baseX,baseY);g.quadraticCurveTo(baseX+w*.07,baseY-h*.2,tipX-bend,tipY+bend);g.stroke();g.strokeStyle=styles[1];g.lineWidth=6;g.beginPath();g.moveTo(baseX,baseY);g.quadraticCurveTo(baseX+w*.07,baseY-h*.2,tipX-bend,tipY+bend);g.stroke();g.strokeStyle='#e5fbffcc';g.lineWidth=1;g.beginPath();g.moveTo(tipX-bend,tipY+bend);g.quadraticCurveTo((tipX+baseX)/2+Math.sin(t*3)*8,(tipY+baseY)/2,tipX,tipY);g.stroke();g.fillStyle=styles[2];g.beginPath();g.ellipse(baseX-w*.08,baseY-h*.01,w*.09,h*.1,-.35,0,Math.PI*2);g.fill();g.beginPath();g.ellipse(baseX+w*.08,baseY-h*.01,w*.08,h*.095,.35,0,Math.PI*2);g.fill();g.restore()}
  bobber(g,w,h,t){const p=this.floatPoint(w,h),colors=[['#e93f36','#fff'],['#e8c548','#162532'],['#f46e22','#fff'],['#6e9aff','#f4f7ff'],['#f3d45b','#412a54'],['#29c0ca','#172939'],['#e8edf2','#f08e36'],['#d957d7','#fff1a8']][state.floats-1],x=p.x,y=p.y+Math.sin(t*4)*3;g.save();g.translate(x,y);g.shadowColor='#001522';g.shadowBlur=6;g.fillStyle=colors[0];g.beginPath();g.moveTo(0,-12);g.bezierCurveTo(10,-4,9,8,0,12);g.bezierCurveTo(-9,8,-10,-4,0,-12);g.fill();g.fillStyle=colors[1];g.fillRect(-7,1,14,4);g.fillStyle='#ffdf73';g.fillRect(-1,-21,2,10);g.restore()}
  drawFish(g,x,y,t,r){const colors=['#a9c4c6','#48a7ff','#bd6cff','#ff8c55','#ffe36b'];const a=Math.sin(t*7)*.18;g.save();g.translate(x+Math.sin(t*2)*20,y+18);g.rotate(a);if(r>=3){g.shadowBlur=r*7;g.shadowColor=colors[r-1]}const fill=r===4?g.createLinearGradient(-30,0,30,0):colors[r-1];if(r===4){fill.addColorStop(0,'#ffcf6d');fill.addColorStop(.5,'#ff6ac1');fill.addColorStop(1,'#7b64ff')}g.fillStyle=fill;g.beginPath();g.ellipse(0,0,27,13,0,0,Math.PI*2);g.fill();g.beginPath();g.moveTo(-23,0);g.lineTo(-39,-14);g.lineTo(-35,0);g.lineTo(-39,14);g.closePath();g.fill();g.fillStyle='#061824';g.beginPath();g.arc(14,-3,2.5,0,Math.PI*2);g.fill();if(r===5){g.fillStyle='#fff4af';for(let i=0;i<8;i++){g.fillRect(Math.sin(t*3+i)*37,Math.cos(t*4+i)*22,2,2)}}g.restore()}
}
const sceneRenderer=new ProceduralScene($('worldCanvas'));
function fishIcon(r){return ['🐠','🐟','🐡','🦈','🐉'][r-1]}
function showCatchDialog(catches){const fish=catches[0],rarity=rarities[fish.rarity-1];$('catchFishImage').src=fishImages[fish.name]||'assets/freshwater-fish.png';$('catchFishImage').alt=fish.name;$('catchFishName').textContent=fish.name;$('catchFishMeta').textContent=`${rarity.name} · ${locations[fish.location].name}`;$('catchFishExtra').textContent=catches.length>1?`Дополнительный улов: ${catches.slice(1).map(f=>f.name).join(', ')}.`:'';$('catch').classList.add('open')}
function pickFish(){
  const max=Math.min(5,state.rods), bonus=Math.max(0,state.rods-1)+Math.max(0,state.baits-1); let weights=[Math.max(18,64-bonus*4),24+bonus,8+bonus,3+Math.ceil(bonus/2),1+Math.floor(bonus/3)]; if(petBonus('luck')){weights=[weights[0]-8,weights[1]+2,weights[2]+2,weights[3]+2,weights[4]+2]}
  const allowed=weights.slice(0,max); let roll=Math.random()*allowed.reduce((a,b)=>a+b,0), rarity=1;
  for(let i=0;i<allowed.length;i++){roll-=allowed[i];if(roll<=0){rarity=i+1;break}}
  const name=locations[state.location].fish[rarity-1]; return {id:Date.now()+Math.random(), name, rarity, clean:false, cuts:0, location:state.location};
}
function startCharge(e){if(e.button!==2||casting)return; e.preventDefault(); charging=true; charge=0; note('Сила заброса растёт… отпустите ПКМ!'); castTimer=setInterval(()=>{charge=Math.min(100,charge+2);$('castPower').style.width=charge+'%';updateDepth()},35)}
function cast(){
  if(!charging)return; charging=false; clearInterval(castTimer); $('castPower').style.width='0%'; if(charge<8){note('Заброс слишком слабый. Удерживайте ПКМ дольше.');return}
  casting=true; sceneRenderer.startCast(charge); note(`Заброс на ${charge}% — ждём поклёвку…`);
  const delay=Math.max(800,(petBonus('speed')?2000:3300)-(state.floats-1)*150)+Math.random()*2500; setTimeout(bite,delay);
}
function bite(){if(!casting)return; sceneRenderer.biting=true;sceneRenderer.fish=pickFish();note('Есть поклёвка! Удерживайте ЛКМ, чтобы подтянуть снасть.'); setTimeout(()=>{if(casting) landFish()},4800)}
function startPull(e){if(e.button!==0||!casting||pulling)return;pulling=true;sceneRenderer.pulling=true;$('equippedRod').classList.add('pulling');reel=0;note('Подтягивайте снасть…');pullTimer=setInterval(()=>{reel=Math.min(100,reel+8);sceneRenderer.reel=reel;updateDepth(true);$('depthNeedle').style.left=(20+reel*.7)+'%';if(reel>=100)landFish()},80)}
function stopPull(e){if(e.button!==0||!pulling)return;pulling=false;sceneRenderer.pulling=false;$('equippedRod').classList.remove('pulling');clearInterval(pullTimer);if(casting)note('Рыба сопротивляется — удерживайте ЛКМ дольше.')}
function landFish(){
  if(!casting)return; const visibleFish=sceneRenderer.fish; casting=false; pulling=false; clearInterval(pullTimer); $('equippedRod').classList.remove('pulling'); sceneRenderer.clear();
  const catches=[]; if(visibleFish)catches.push(visibleFish); while(catches.length<state.hooks)catches.push(pickFish()); state.inventory.unshift(...catches);
  catches.forEach(f=>{if(!state.discovered.includes(f.name))state.discovered.push(f.name)}); state.xp+=catches.reduce((sum,f)=>sum+f.rarity*24,0); advanceContract(catches.length); const top=catches.reduce((a,b)=>a.rarity>b.rarity?a:b); const r=rarities[top.rarity-1];
  state.best=top.name; $('rarityDisplay').innerHTML=`<i style="background:${r.color};box-shadow:0 0 9px ${r.color}"></i><span>${r.name}: ${top.name}</span>`; note(`Улов: ${catches.map(x=>x.name).join(', ')}. Откройте Садок!`); state.journal.unshift(`Поймано: ${catches.map(x=>x.name).join(', ')} (${locations[state.location].name})`); state.journal=state.journal.slice(0,30); render(); showCatchDialog(catches);
}
function updateDepth(pulling=false){const point=Math.min(90,15+(pulling?65:charge*.65));$('depthNeedle').style.left=point+'%';$('depthNeedle').style.height=(pulling?70:28+charge*.45)+'%'}
const cutsNeeded=()=>Math.max(1,4-Math.floor((state.knives+1)/3));
function advanceContract(count){state.contract.progress+=count;if(state.contract.progress<state.contract.target)return;const reward=state.contract.reward;state.coins+=reward;state.total+=reward;state.xp+=80;state.contract={target:state.contract.target+4,progress:0,reward:Math.round(reward*1.6)};state.journal.unshift(`Контракт выполнен: +${reward} монет и 80 XP.`);note(`Контракт выполнен! +${reward} ◉`)}
function settleAuctions(){const now=Date.now();state.auctions=state.auctions.filter(a=>{if(a.endsAt>now)return true;state.coins+=a.bid;state.total+=a.bid;state.auctionLog.unshift(`${a.fish.name} продана на аукционе за ${a.bid} ◉.`);return false});state.auctionLog=state.auctionLog.slice(0,4)}
function auctionFish(id){const i=state.inventory.findIndex(f=>f.id==id),fish=state.inventory[i];if(!fish||!fish.clean)return;state.inventory.splice(i,1);const bid=Math.round(price(fish)*(1.3+fish.rarity*.18));state.auctions.unshift({id:Date.now()+Math.random(),fish,bid,bidders:1,endsAt:Date.now()+45000});state.journal.unshift(`Рыба выставлена на аукцион: ${fish.name}.`);openModal('auction')}
function auctionTick(){let changed=false;state.auctions.forEach(a=>{if(a.endsAt>Date.now()&&Math.random()<.45){a.bid+=Math.max(10,Math.round(a.bid*.08));a.bidders++;changed=true}});const active=state.auctions.length;settleAuctions();if(active!==state.auctions.length){note('Аукционный лот продан — монеты зачислены.');render();return}if(changed&&$('auction').classList.contains('open'))renderAuctions();if(changed)save()}
setInterval(auctionTick,1500);
function cutFish(id){const f=state.inventory.find(x=>x.id==id);if(!f)return;if(state.knives<Math.min(f.rarity,5)){note('Нужен нож поострее!');return}f.cuts++;if(f.cuts>=cutsNeeded()){f.clean=true;state.journal.unshift(`Рыба очищена: ${f.name}`);note(`${f.name} готова к продаже.`)}render()}
function autoClean(){let made=0;state.inventory.filter(f=>!f.clean&&state.knives>=f.rarity).forEach(f=>{f.clean=true;made++}); note(made?`Самоочистка: подготовлено рыб — ${made}.`:'Нет рыбы для очистки: нужен нож поострее.');render()}
function price(f){return Math.round(rarities[f.rarity-1].value*(petBonus('money')?1.2:1))}
function sell(id){const i=state.inventory.findIndex(x=>x.id==id);if(i<0)return;const f=state.inventory[i];if(!f.clean){note('Сначала разделайте рыбу.');return}state.inventory.splice(i,1);const earned=price(f);state.coins+=earned;state.total+=earned;state.journal.unshift(`Продано: ${f.name} за ${earned} монет.`);render()}
function sellAll(){const cleaned=state.inventory.filter(f=>f.clean);if(!cleaned.length){note('В садке нет очищенной рыбы.');return}const earned=cleaned.reduce((n,f)=>n+price(f),0);state.inventory=state.inventory.filter(f=>!f.clean);state.coins+=earned;state.total+=earned;state.journal.unshift(`Продано очищенной рыбы на ${earned} монет.`);render()}
function renderKeepnet(){const root=$('keepnetList');root.innerHTML=state.inventory.length?state.inventory.map(f=>{const r=rarities[f.rarity-1],needed=cutsNeeded();return `<article class="fish-card" style="--rarity:${r.color}"><span class="fish-icon">${fishIcon(f.rarity)}</span><div><b style="color:${r.color}">${f.name}</b><br><small>${r.name} · ${locations[f.location].name}${f.clean?' · очищена':''}</small>${!f.clean?`<div class="cut-progress"><i style="width:${f.cuts/needed*100}%"></i></div>`:''}</div>${f.clean?`<div class="fish-actions"><button onclick="sell('${f.id}')">Продать ${price(f)} ◉</button><button class="auction-button" onclick="auctionFish('${f.id}')">На аукцион</button></div>`:`<button onclick="cutFish('${f.id}')">Разделать ${f.cuts}/${needed}</button>`}</article>`}).join(''):'<p class="muted">Садок пока пуст — пора забросить удочку.</p>'}
function renderMap(){$('locationGrid').innerHTML=Object.entries(locations).map(([key,l])=>{const needed=locationLevels[key],locked=playerLevel()<needed;return `<article class="location-card ${key}"><h3>${l.name}</h3><p>${l.desc}<br><small>Требуется уровень ${needed}</small></p><button onclick="changeLocation('${key}')" ${(state.location===key||locked)?'disabled':''}>${state.location===key?'Вы здесь':locked?'Закрыто':'Отправиться'}</button></article>`}).join('')}
function changeLocation(key){if(key===state.location)return;if(playerLevel()<locationLevels[key]){note(`Для этой локации нужен уровень ${locationLevels[key]}.`);return}state.location=key;state.journal.unshift(`Вы отправились: ${locations[key].name}.`);closeAll();$('scene').animate([{opacity:.1},{opacity:1}],{duration:600});render();note(`Новая локация: ${locations[key].name}.`) }
function renderBag(){$('bagContent').innerHTML=[['🎣','Удочка',gear.rods[state.rods-1][0],`Шанс на трофей: +${state.rods-1}`],['🪝','Крючки',gear.hooks[state.hooks-1][0],`Рыб за заброс: ${state.hooks}`],['🔪','Нож',gear.knives[state.knives-1][0],`Разделка: ${cutsNeeded()} действия`],['🎈','Поплавок',gear.floats[state.floats-1][0],`Поклёвка быстрее: ${state.floats-1}`],['🪱','Наживка',gear.baits[state.baits-1][0],`Редкость улова: +${state.baits-1}`]].map(x=>`<div><b>${x[0]} ${x[1]}</b><p>${x[2]}<br><small>${x[3]}</small></p></div>`).join('')}
function renderProfile(){$('profileContent').innerHTML=`<div><b>Рыбак · уровень ${playerLevel()}</b><p>XP: ${state.xp}<br>Баланс: ${state.coins.toLocaleString('ru-RU')} ◉</p></div><div><b>Коллекционер</b><p>Открыто рыб: ${state.discovered.length} / 15<br>Лучший улов: ${state.best}</p></div><div><b>Экипировка</b><p>Удочка ${roman(state.rods)} · Нож ${roman(state.knives)}<br>Крючки ${roman(state.hooks)} · Поплавок ${roman(state.floats)}</p></div>`}
function renderJournal(){$('journalContent').innerHTML=state.journal.map(x=>`<p>${x}</p>`).join('')}
function renderIndex(){const all=Object.values(locations).flatMap(l=>l.fish.map((name,i)=>({name,rarity:i+1})));$('indexContent').innerHTML=all.map(f=>{const known=state.discovered.includes(f.name),r=rarities[f.rarity-1],visual=known?`<img class="index-photo" src="${fishImages[f.name]}" alt="${f.name}">`:`<span class="fish-icon">🐟</span>`;return `<article class="index-card ${known?'':'locked'}">${visual}<strong style="color:${known?r.color:'inherit'}">${known?f.name:'???'}</strong><small>${known?r.name:'Неизвестная рыба'}</small></article>`}).join('')}
function renderShop(){const list=gear[shop],descriptions={rods:(level)=>`Открывает рыбу ${tierName(level)} редкости и повышает шанс трофея.`,knives:()=>`Ускоряет обработку: сейчас ${cutsNeeded()} действия на рыбу.`,hooks:(level)=>`Позволяет поймать до ${level} рыб за один заброс.`,floats:(level)=>`Ускоряет поклёвку на ${level-1} ступеней.`,baits:(level)=>`Повышает шанс редкой рыбы на ${level-1} ступеней.`};$('shopContent').innerHTML=list.map((g,i)=>{const level=i+1,owned=level<=state[shop],next=level===state[shop]+1,cost=g[1],picture=shop==='rods'?`<img class="shop-photo" src="${rodImages[i]}" alt="${g[0]}">`:'';return `<article class="shop-card ${shop} ${level===state[shop]?'current':''}">${picture}<small>УРОВЕНЬ ${roman(level)}</small><h3>${g[0]}</h3><p>${descriptions[shop](level)}</p><button ${(!next||state.coins<cost)?'disabled':''} onclick="buy('${shop}',${level})">${level===state[shop]?'Экипировано':owned?'Куплено':next?`Купить · ${cost} ◉`:'Сначала предыдущий уровень'}</button></article>`}).join('');document.querySelectorAll('[data-shop]').forEach(b=>b.classList.toggle('active',b.dataset.shop===shop))}
function renderAuctions(){const root=$('auctionContent'),now=Date.now();root.innerHTML=state.auctions.length?state.auctions.map(a=>`<article class="auction-card"><span>${fishIcon(a.fish.rarity)}</span><div><b>${a.fish.name}</b><small>${a.bidders} покупателя · ${Math.max(1,Math.ceil((a.endsAt-now)/1000))} сек.</small></div><strong>${a.bid} ◉</strong></article>`).join(''):`<p class="muted">Нет активных лотов. Очистите рыбу и отправьте её на аукцион из садка.</p>`;if(state.auctionLog.length)root.innerHTML+=`<div class="auction-log">${state.auctionLog.map(x=>`<small>${x}</small>`).join('')}</div>`}
function buy(type,level){const item=gear[type][level-1];if(state[type]!==level-1||state.coins<item[1])return;state.coins-=item[1];state[type]=level;state.journal.unshift(`Куплено: ${item[0]}.`);render()}
function renderPets(){$('petContent').innerHTML=pets.map(p=>{const owned=state.pets.some(x=>x.name===p.name),open=state.total>=1000000;return `<article class="pet-card ${open?'':'locked'}"><span class="fish-icon">${p.icon}</span><h3>${p.name}</h3><p>${p.bonus}<br>Стоимость: ${p.price.toLocaleString('ru-RU')} ◉</p><button ${(!open||owned||state.coins<p.price)?'disabled':''} onclick="buyPet('${p.name}')">${owned?'Рядом с вами':open?`Подружиться · ${p.price} ◉`:'Доступно после 1 000 000 ◉'}</button></article>`}).join('')}
function buyPet(name){const p=pets.find(x=>x.name===name);if(!p||state.coins<p.price||state.total<1000000)return;state.coins-=p.price;state.pets.push(p);state.journal.unshift(`Питомец присоединился: ${p.name}.`);render()}
document.addEventListener('contextmenu',e=>e.preventDefault()); window.addEventListener('mousedown',startCharge);window.addEventListener('mousedown',startPull);window.addEventListener('mouseup',e=>{if(e.button===2)cast();if(e.button===0)stopPull(e)});$('autoClean').onclick=autoClean;$('sellAll').onclick=sellAll;document.querySelectorAll('[data-modal]').forEach(b=>b.onclick=()=>{if(b.dataset.shop){shop=b.dataset.shop}openModal(b.dataset.modal)});document.querySelectorAll('.close,.close-dialog').forEach(b=>b.onclick=closeAll);document.querySelectorAll('.shop-tabs button').forEach(b=>b.onclick=()=>{shop=b.dataset.shop;renderShop()});window.cutFish=cutFish;window.sell=sell;window.changeLocation=changeLocation;window.buy=buy;window.buyPet=buyPet;render();
