const $ = (id) => document.getElementById(id);
const SAVE_KEY = 'sea-resort-fishing-v1';
const rarities = [
  {name:'Обычная', color:'#b9d5d7', value:35}, {name:'Редкая', color:'#55aaff', value:110},
  {name:'Эпическая', color:'#bf79ff', value:380}, {name:'Мифическая', color:'#ff9271', value:1250}, {name:'Легендарная', color:'#ffe06a', value:4200}
];
const locations = {
  pier:{name:'Пирс', sub:'тихая бухта', desc:'Стартовая бухта с доступной рыбой и лёгкой рябью.', fish:['Серебряная кефаль','Янтарный окунь','Полуночная камбала','Коралловый морской язык','Золотой морской конёк']},
  ocean:{name:'Океан', sub:'открытое море', desc:'Глубина, волны и более крупные трофеи.', fish:['Синяя макрель','Штормовой тунец','Призрачный скат','Китовая рыба-луна','Королевский марлин']},
  swamp:{name:'Болото', sub:'туманные топи', desc:'Мутные воды, камыши и редкие болотные виды.', fish:['Болотная плотва','Теневой сом','Нефритовая щука','Древний угорь','Царь-аллигатор']}
};
const gear = {
  rods:[['Деревянная удочка',0],['Железная удочка',120],['Золотая удочка',390],['Алмазная удочка',1200],['Рубиновая удочка',3800]],
  knives:[['Рыбацкий нож',0],['Перламутровый нож',140],['Приливный клинок',450],['Нож бездны',1400],['Солнечный тесак',4400]],
  hooks:[['Медный поплавок',0],['Лунный крючок',110],['Звёздная связка',350],['Туманная сеть',1100],['Галактическая стая',3600]]
};
const pets = [{name:'Выдра Искра',icon:'🦦',bonus:'+20% к продаже',price:1000000,type:'money'}, {name:'Чайка Ветра',icon:'🕊️',bonus:'быстрее поклёвка',price:1250000,type:'speed'}, {name:'Морской лис',icon:'🦊',bonus:'+10% к редкой рыбе',price:1500000,type:'luck'}];
const initial = {coins:30, rods:1, knives:1, hooks:1, location:'pier', inventory:[], discovered:[], journal:['Вы прибыли на Морской курорт.'], pets:[], total:30, best:'—'};
let state; try { state={...initial,...JSON.parse(localStorage.getItem(SAVE_KEY))}; } catch { state={...initial}; }
let charge=0, charging=false, castTimer, casting=false, pulling=false, pullTimer, reel=0, session=0, shop='rods';
const save=()=>localStorage.setItem(SAVE_KEY,JSON.stringify(state));
const roman=(n)=>['I','II','III','IV','V'][n-1];
const petBonus=(type)=>state.pets.some(p=>p.type===type);
function render(){
  $('coins').textContent=state.coins.toLocaleString('ru-RU'); $('fishCount').textContent=state.inventory.length;
  $('rodLevel').textContent=roman(state.rods); $('knifeLevel').textContent=roman(state.knives); $('hookLevel').textContent=roman(state.hooks);
  $('hookName').textContent=gear.hooks[state.hooks-1][0]; $('locationLabel').textContent=`${locations[state.location].name} · ${locations[state.location].sub}`;
  $('bestCatch').textContent=state.best; $('game').className=`game location-${state.location}`;
  renderKeepnet(); renderMap(); renderBag(); renderProfile(); renderJournal(); renderIndex(); renderShop(); renderPets(); save();
}
function openModal(id){ $(id).classList.add('open'); render(); }
function closeAll(){document.querySelectorAll('.modal').forEach(x=>x.classList.remove('open'))}
function note(text){$('castMessage').textContent=text}
function time(){session++; $('sessionTime').textContent=`${String(Math.floor(session/60)).padStart(2,'0')}:${String(session%60).padStart(2,'0')}`}
setInterval(time,1000);
class ProceduralScene {
  constructor(canvas){this.c=canvas;this.x=50;this.y=61;this.cast=0;this.biting=false;this.pulling=false;this.fish=null;this.t0=performance.now();this.resize();addEventListener('resize',()=>this.resize());requestAnimationFrame(t=>this.frame(t))}
  resize(){const d=Math.min(devicePixelRatio||1,2),r=this.c.getBoundingClientRect();this.w=Math.max(1,r.width);this.h=Math.max(1,r.height);this.c.width=this.w*d;this.c.height=this.h*d;this.g=this.c.getContext('2d');this.g.setTransform(d,0,0,d,0,0)}
  startCast(power){this.cast=power;this.x=31+power*.55;this.y=57+power*.075;this.biting=false;this.fish=null}
  clear(){this.cast=0;this.biting=false;this.pulling=false;this.fish=null}
  frame(now){const t=(now-this.t0)/1000,g=this.g,w=this.w,h=this.h,loc=state.location;g.clearRect(0,0,w,h);this.sky(g,w,h,t,loc);this.water(g,w,h,t,loc);this.pier(g,w,h);this.rod(g,w,h,t);if(this.cast)this.bobber(g,w,h,t);if(this.biting&&this.fish)this.drawFish(g,w*this.x/100,h*this.y/100+28,t,this.fish.rarity);requestAnimationFrame(n=>this.frame(n))}
  sky(g,w,h,t,loc){const sets={pier:['#103c71','#ef9274','#ffd68a'],ocean:['#06345f','#6e9fc0','#d5dbca'],swamp:['#1a302a','#63765c','#b0a77c']}[loc];const sky=g.createLinearGradient(0,0,0,h*.58);sky.addColorStop(0,sets[0]);sky.addColorStop(.72,sets[1]);sky.addColorStop(1,sets[2]);g.fillStyle=sky;g.fillRect(0,0,w,h*.6);const sx=w*.77,sy=h*.22;const sun=g.createRadialGradient(sx,sy,2,sx,sy,h*.11);sun.addColorStop(0,'#fff9cf');sun.addColorStop(.35,'#ffe8a4');sun.addColorStop(1,'#ffcf8400');g.fillStyle=sun;g.fillRect(0,0,w,h*.6);g.fillStyle='rgba(255,246,232,.35)';for(let i=0;i<5;i++){let x=((i*263+t*9)% (w+220))-110,y=h*(.12+i*.055);g.beginPath();g.ellipse(x,y,90,12,0,0,Math.PI*2);g.ellipse(x+45,y-10,38,20,0,0,Math.PI*2);g.fill()}g.fillStyle=loc==='swamp'?'#244437':'#1a5660';g.beginPath();g.moveTo(0,h*.51);for(let x=0;x<=w;x+=35){const y=h*(.43+((Math.sin(x*.027)+Math.sin(x*.071))*0.025));g.lineTo(x,y)}g.lineTo(w,h*.57);g.lineTo(0,h*.57);g.fill();if(loc!=='swamp'){g.fillStyle='#263f4b';g.beginPath();g.moveTo(w*.73,h*.47);g.lineTo(w*.76,h*.39);g.lineTo(w*.79,h*.47);g.fill();g.fillRect(w*.755,h*.445,w*.045,2)}}
  water(g,w,h,t,loc){const top=h*.51,sets={pier:['#1786a0','#043150'],ocean:['#087da6','#012642'],swamp:['#496f49','#102d2b']}[loc],grad=g.createLinearGradient(0,top,0,h);grad.addColorStop(0,sets[0]);grad.addColorStop(1,sets[1]);g.fillStyle=grad;g.fillRect(0,top,w,h-top);for(let row=0;row<18;row++){const y=top+row*18;g.strokeStyle=`rgba(210,255,255,${.11-row*.004})`;g.lineWidth=1;g.beginPath();for(let x=0;x<=w;x+=8){const wave=Math.sin(x*.025+t*(1.5+(loc==='ocean'?1:0))+row*.8)*((row+2)/10)+Math.sin(x*.07-t*1.7)*1.5; x?g.lineTo(x,y+wave):g.moveTo(x,y+wave)}g.stroke()}const rx=w*.77;for(let i=0;i<18;i++){const yy=top+18+i*i*1.5;const ww=Math.max(3,5+i*5);g.fillStyle=`rgba(255,239,178,${.22-i*.01})`;g.fillRect(rx-ww/2+Math.sin(t*3+i)*5,yy,ww,1.5)}if(this.cast){const x=w*this.x/100,y=h*this.y/100;for(let i=0;i<3;i++){const r=((t*42+i*19)%72);g.strokeStyle=`rgba(220,255,255,${.5-r/145})`;g.beginPath();g.ellipse(x,y,r,r*.3,0,0,Math.PI*2);g.stroke()}}}
  pier(g,w,h){g.save();g.fillStyle='#51311f';g.beginPath();g.moveTo(0,h);g.lineTo(w,h);g.lineTo(w*.72,h*.78);g.lineTo(w*.28,h*.78);g.closePath();g.fill();g.strokeStyle='#9a6139';g.lineWidth=3;for(let i=0;i<9;i++){const x=w*.28+(w*.44/8)*i;g.beginPath();g.moveTo(x,h*.78);g.lineTo(x+(x-w*.5)*.7,h);g.stroke()}g.restore()}
  rod(g,w,h,t){const baseX=w*.51,baseY=h*1.03,tipX=this.cast?w*this.x/100:baseX+w*.13,tipY=this.cast?h*this.y/100:baseY-h*.33;const bend=this.biting?34:this.pulling?21:8;g.save();g.lineCap='round';g.strokeStyle='#25130b';g.lineWidth=13;g.beginPath();g.moveTo(baseX,baseY);g.quadraticCurveTo(baseX+w*.07,baseY-h*.2,tipX-bend,tipY+bend);g.stroke();g.strokeStyle='#d69a54';g.lineWidth=6;g.beginPath();g.moveTo(baseX,baseY);g.quadraticCurveTo(baseX+w*.07,baseY-h*.2,tipX-bend,tipY+bend);g.stroke();g.strokeStyle='#d8f9ffcc';g.lineWidth=1;g.beginPath();g.moveTo(tipX-bend,tipY+bend);g.quadraticCurveTo((tipX+baseX)/2+Math.sin(t*3)*8,(tipY+baseY)/2,tipX,tipY);g.stroke();g.fillStyle='#c98c64';g.beginPath();g.ellipse(baseX-w*.08,baseY-h*.01,w*.09,h*.1,-.35,0,Math.PI*2);g.fill();g.beginPath();g.ellipse(baseX+w*.08,baseY-h*.01,w*.08,h*.095,.35,0,Math.PI*2);g.fill();g.restore()}
  bobber(g,w,h,t){const x=w*this.x/100,y=h*this.y/100+Math.sin(t*4)*3;g.save();g.translate(x,y);g.fillStyle='#ff5b4f';g.beginPath();g.arc(0,0,7,Math.PI,0);g.fill();g.fillStyle='#fff';g.fillRect(-7,0,14,6);g.restore()}
  drawFish(g,x,y,t,r){const colors=['#a9c4c6','#48a7ff','#bd6cff','#ff8c55','#ffe36b'];const a=Math.sin(t*7)*.18;g.save();g.translate(x+Math.sin(t*2)*20,y+18);g.rotate(a);if(r>=3){g.shadowBlur=r*7;g.shadowColor=colors[r-1]}const fill=r===4?g.createLinearGradient(-30,0,30,0):colors[r-1];if(r===4){fill.addColorStop(0,'#ffcf6d');fill.addColorStop(.5,'#ff6ac1');fill.addColorStop(1,'#7b64ff')}g.fillStyle=fill;g.beginPath();g.ellipse(0,0,27,13,0,0,Math.PI*2);g.fill();g.beginPath();g.moveTo(-23,0);g.lineTo(-39,-14);g.lineTo(-35,0);g.lineTo(-39,14);g.closePath();g.fill();g.fillStyle='#061824';g.beginPath();g.arc(14,-3,2.5,0,Math.PI*2);g.fill();if(r===5){g.fillStyle='#fff4af';for(let i=0;i<8;i++){g.fillRect(Math.sin(t*3+i)*37,Math.cos(t*4+i)*22,2,2)}}g.restore()}
}
const sceneRenderer=new ProceduralScene($('worldCanvas'));
function fishIcon(r){return ['🐠','🐟','🐡','🦈','🐉'][r-1]}
function pickFish(){
  const max=Math.min(5,state.rods); let weights=[64,24,8,3,1]; if(petBonus('luck')){weights=[56,26,11,5,2]}
  const allowed=weights.slice(0,max); let roll=Math.random()*allowed.reduce((a,b)=>a+b,0), rarity=1;
  for(let i=0;i<allowed.length;i++){roll-=allowed[i];if(roll<=0){rarity=i+1;break}}
  const name=locations[state.location].fish[rarity-1]; return {id:Date.now()+Math.random(), name, rarity, clean:false, cuts:0, location:state.location};
}
function startCharge(e){if(e.button!==2||casting)return; e.preventDefault(); charging=true; charge=0; note('Сила заброса растёт… отпустите ПКМ!'); castTimer=setInterval(()=>{charge=Math.min(100,charge+2);$('castPower').style.width=charge+'%';updateDepth()},35)}
function cast(){
  if(!charging)return; charging=false; clearInterval(castTimer); $('castPower').style.width='0%'; if(charge<8){note('Заброс слишком слабый. Удерживайте ПКМ дольше.');return}
  casting=true; sceneRenderer.startCast(charge); note(`Заброс на ${charge}% — ждём поклёвку…`);
  const delay=(petBonus('speed')?2000:3300)+Math.random()*2500; setTimeout(bite,delay);
}
function bite(){if(!casting)return; sceneRenderer.biting=true;sceneRenderer.fish=pickFish();note('Есть поклёвка! Удерживайте ЛКМ, чтобы подтянуть снасть.'); setTimeout(()=>{if(casting) landFish()},4800)}
function startPull(e){if(e.button!==0||!casting||pulling)return;pulling=true;sceneRenderer.pulling=true;reel=0;note('Подтягивайте снасть…');pullTimer=setInterval(()=>{reel=Math.min(100,reel+8);updateDepth(true);$('depthNeedle').style.left=(20+reel*.7)+'%';if(reel>=100)landFish()},80)}
function stopPull(e){if(e.button!==0||!pulling)return;pulling=false;sceneRenderer.pulling=false;clearInterval(pullTimer);if(casting)note('Рыба сопротивляется — удерживайте ЛКМ дольше.')}
function landFish(){
  if(!casting)return; const visibleFish=sceneRenderer.fish; casting=false; pulling=false; clearInterval(pullTimer); sceneRenderer.clear();
  const catches=[]; if(visibleFish)catches.push(visibleFish); while(catches.length<state.hooks)catches.push(pickFish()); state.inventory.unshift(...catches);
  catches.forEach(f=>{if(!state.discovered.includes(f.name))state.discovered.push(f.name)}); const top=catches.reduce((a,b)=>a.rarity>b.rarity?a:b); const r=rarities[top.rarity-1];
  state.best=top.name; $('rarityDisplay').innerHTML=`<i style="background:${r.color};box-shadow:0 0 9px ${r.color}"></i><span>${r.name}: ${top.name}</span>`; note(`Улов: ${catches.map(x=>x.name).join(', ')}. Откройте Садок!`); state.journal.unshift(`Поймано: ${catches.map(x=>x.name).join(', ')} (${locations[state.location].name})`); state.journal=state.journal.slice(0,30); render();
}
function updateDepth(pulling=false){const point=Math.min(90,15+(pulling?65:charge*.65));$('depthNeedle').style.left=point+'%';$('depthNeedle').style.height=(pulling?70:28+charge*.45)+'%'}
function cutFish(id){const f=state.inventory.find(x=>x.id==id);if(!f)return;if(state.knives<f.rarity){note('Нужен нож поострее!');return}f.cuts++;if(f.cuts>=3){f.clean=true;state.journal.unshift(`Рыба очищена: ${f.name}`);note(`${f.name} готова к продаже.`)}render()}
function autoClean(){let made=0;state.inventory.filter(f=>!f.clean&&state.knives>=f.rarity).forEach(f=>{f.clean=true;made++}); note(made?`Самоочистка: подготовлено рыб — ${made}.`:'Нет рыбы для очистки: нужен нож поострее.');render()}
function price(f){return Math.round(rarities[f.rarity-1].value*(petBonus('money')?1.2:1))}
function sell(id){const i=state.inventory.findIndex(x=>x.id==id);if(i<0)return;const f=state.inventory[i];if(!f.clean){note('Сначала разделайте рыбу.');return}state.inventory.splice(i,1);const earned=price(f);state.coins+=earned;state.total+=earned;state.journal.unshift(`Продано: ${f.name} за ${earned} монет.`);render()}
function sellAll(){const cleaned=state.inventory.filter(f=>f.clean);if(!cleaned.length){note('В садке нет очищенной рыбы.');return}const earned=cleaned.reduce((n,f)=>n+price(f),0);state.inventory=state.inventory.filter(f=>!f.clean);state.coins+=earned;state.total+=earned;state.journal.unshift(`Продано очищенной рыбы на ${earned} монет.`);render()}
function renderKeepnet(){const root=$('keepnetList');root.innerHTML=state.inventory.length?state.inventory.map(f=>{const r=rarities[f.rarity-1];return `<article class="fish-card" style="--rarity:${r.color}"><span class="fish-icon">${fishIcon(f.rarity)}</span><div><b style="color:${r.color}">${f.name}</b><br><small>${r.name} · ${locations[f.location].name}${f.clean?' · очищена':''}</small>${!f.clean?`<div class="cut-progress"><i style="width:${f.cuts/3*100}%"></i></div>`:''}</div>${f.clean?`<button onclick="sell('${f.id}')">Продать ${price(f)} ◉</button>`:`<button onclick="cutFish('${f.id}')">Разделать ${f.cuts}/3</button>`}</article>`}).join(''):'<p class="muted">Садок пока пуст — пора забросить удочку.</p>'}
function renderMap(){$('locationGrid').innerHTML=Object.entries(locations).map(([key,l])=>`<article class="location-card ${key}"><h3>${l.name}</h3><p>${l.desc}</p><button onclick="changeLocation('${key}')" ${state.location===key?'disabled':''}>${state.location===key?'Вы здесь':'Отправиться'}</button></article>`).join('')}
function changeLocation(key){if(key===state.location)return;state.location=key;state.journal.unshift(`Вы отправились: ${locations[key].name}.`);closeAll();$('scene').animate([{opacity:.1},{opacity:1}],{duration:600});render();note(`Новая локация: ${locations[key].name}.`) }
function renderBag(){$('bagContent').innerHTML=[['🎣','Удочка',gear.rods[state.rods-1][0],`Глубина и редкость: ${state.rods}/5`],['🪝','Крючки',gear.hooks[state.hooks-1][0],`Рыб за заброс: ${state.hooks}`],['🔪','Нож',gear.knives[state.knives-1][0],`Разделка до ${rarities[state.knives-1].name.toLowerCase()}`]].map(x=>`<div><b>${x[0]} ${x[1]}</b><p>${x[2]}<br><small>${x[3]}</small></p></div>`).join('')}
function renderProfile(){$('profileContent').innerHTML=`<div><b>Морской рыбак</b><p>Баланс: ${state.coins.toLocaleString('ru-RU')} ◉<br>Заработано всего: ${state.total.toLocaleString('ru-RU')} ◉</p></div><div><b>Коллекционер</b><p>Открыто рыб: ${state.discovered.length} / 15<br>Лучший улов: ${state.best}</p></div><div><b>Экипировка</b><p>Удочка ${roman(state.rods)} · Нож ${roman(state.knives)} · Крючки ${roman(state.hooks)}</p></div>`}
function renderJournal(){$('journalContent').innerHTML=state.journal.map(x=>`<p>${x}</p>`).join('')}
function renderIndex(){const all=Object.values(locations).flatMap(l=>l.fish.map((name,i)=>({name,rarity:i+1})));$('indexContent').innerHTML=all.map(f=>{const known=state.discovered.includes(f.name),r=rarities[f.rarity-1];return `<article class="index-card ${known?'':'locked'}"><span class="fish-icon">${known?fishIcon(f.rarity):'🐟'}</span><strong style="color:${known?r.color:'inherit'}">${known?f.name:'???'}</strong><small>${known?r.name:'Неизвестная рыба'}</small></article>`}).join('')}
function renderShop(){const list=gear[shop];$('shopContent').innerHTML=list.map((g,i)=>{const level=i+1,owned=level<=state[shop],next=level===state[shop]+1,cost=g[1],style=shop==='hooks'?'hooks':shop==='knives'?'knives':'rods';const desc=shop==='rods'?`Открывает глубину и рыбу ${rarities[i].name.toLowerCase()} редкости.`:shop==='knives'?`Разделывает рыбу до ${rarities[i].name.toLowerCase()} редкости.`:`Позволяет поймать до ${level} рыб за один заброс.`;return `<article class="shop-card ${style} ${level===state[shop]?'current':''}"><small>УРОВЕНЬ ${roman(level)}</small><h3>${g[0]}</h3><p>${desc}</p><button ${(!next||state.coins<cost)?'disabled':''} onclick="buy('${shop}',${level})">${level===state[shop]?'Экипировано':owned?'Куплено':next?`Купить · ${cost} ◉`:'Сначала предыдущий уровень'}</button></article>`}).join('');document.querySelectorAll('[data-shop]').forEach(b=>b.classList.toggle('active',b.dataset.shop===shop))}
function buy(type,level){const item=gear[type][level-1];if(state[type]!==level-1||state.coins<item[1])return;state.coins-=item[1];state[type]=level;state.journal.unshift(`Куплено: ${item[0]}.`);render()}
function renderPets(){$('petContent').innerHTML=pets.map(p=>{const owned=state.pets.some(x=>x.name===p.name),open=state.total>=1000000;return `<article class="pet-card ${open?'':'locked'}"><span class="fish-icon">${p.icon}</span><h3>${p.name}</h3><p>${p.bonus}<br>Стоимость: ${p.price.toLocaleString('ru-RU')} ◉</p><button ${(!open||owned||state.coins<p.price)?'disabled':''} onclick="buyPet('${p.name}')">${owned?'Рядом с вами':open?`Подружиться · ${p.price} ◉`:'Доступно после 1 000 000 ◉'}</button></article>`}).join('')}
function buyPet(name){const p=pets.find(x=>x.name===name);if(!p||state.coins<p.price||state.total<1000000)return;state.coins-=p.price;state.pets.push(p);state.journal.unshift(`Питомец присоединился: ${p.name}.`);render()}
document.addEventListener('contextmenu',e=>e.preventDefault()); window.addEventListener('mousedown',startCharge);window.addEventListener('mousedown',startPull);window.addEventListener('mouseup',e=>{if(e.button===2)cast();if(e.button===0)stopPull(e)});$('autoClean').onclick=autoClean;$('sellAll').onclick=sellAll;document.querySelectorAll('[data-modal]').forEach(b=>b.onclick=()=>{if(b.dataset.shop){shop=b.dataset.shop}openModal(b.dataset.modal)});document.querySelectorAll('.close').forEach(b=>b.onclick=closeAll);document.querySelectorAll('.shop-tabs button').forEach(b=>b.onclick=()=>{shop=b.dataset.shop;renderShop()});window.cutFish=cutFish;window.sell=sell;window.changeLocation=changeLocation;window.buy=buy;window.buyPet=buyPet;render();
