const assert=require('node:assert/strict');
const fs=require('node:fs');
const html=fs.readFileSync('index.html','utf8');
const script=fs.readFileSync('script.js','utf8');
const menu=html.match(/<nav class="left-menu"[\s\S]*?<\/nav>/)?.[0]||'';
const menuTargets=[...menu.matchAll(/data-modal="([^"]+)"/g)].map(match=>match[1]);
assert.deepEqual(menuTargets,['keepnet','base','profile','journal'],'sidebar must contain only quick actions');
const base=html.slice(html.indexOf('id="base"'),html.indexOf('<div class="modal" id="keepnet"'));
const baseTargets=[...base.matchAll(/data-modal="([^"]+)"/g)].map(match=>match[1]);
assert.deepEqual(baseTargets,['shops','bag','index','pets','map','world','auction','progress'],'all base links must remain');
for(const id of baseTargets)assert.ok(html.includes(`id="${id}"`),`missing modal for ${id}`);
assert.match(script,/querySelectorAll\('\[data-modal\]'\)/,'base links need a click handler');
console.log('Base navigation is complete.');
