const assert=require('node:assert/strict');
const fs=require('node:fs');
const source=fs.readFileSync('script.js','utf8');
const readObject=(start,end)=>Function(`return (${source.slice(source.indexOf(start)+start.length,source.indexOf(end,source.indexOf(start))).trim().replace(/;$/,'')})`)();
const regions=readObject('const travelRegions=','\nObject.entries(travelRegions)');
const rarities=readObject('const exoticRarities=','\nconst travelRegions=');
assert.equal(Object.keys(regions).length,5,'five regional maps are required');
assert.equal(Object.values(regions).reduce((total,region)=>total+region.spots.length,0),25,'each region needs five locations');
assert.equal(Object.keys(rarities).length,15,'fifteen exotic fish are required');
assert.match(source,/stayCost:data\.cost\+index\*120/,'locations need different daily rates');
assert.match(source,/days\*target\.stayCost/,'trip cost must depend on selected days and location');
assert.match(source,/days\*86400000/,'trip duration must be stored in calendar days');
for(let number=37;number<=51;number++)assert.match(source,new RegExp(`fish-${number}-`),`missing fish image ${number}`);
console.log('World expedition data is complete.');
